import { PioneerItem } from "@/types/pioneer";

export const MOCK_PIONEERS_DATA: PioneerItem[] = [
  {
    id: "open-bionics",
    initials: "OB",
    name: "Open Bionics",
    website: "openbionics.com",
    location: "Bristol, United Kingdom",
    productCount: 1,
    claimedStatus: "Claimed",
    subscriptionStatus: "Active",
    verificationStatus: "Verified",
    createdAt: "2023-06-01",
    bio: "Affordable, lightweight bionic hands for upper limb amputees.",
    country: "United Kingdom",
    region: "England",
    city: "Bristol",
    products: [
      {
        id: "p-1",
        name: "Hero Arm",
        category: "Bionic Hand",
        status: "Active",
      },
    ],
    subscriptionPlan: "Annual",
    subscriptionStartDate: "2023-06-01",
    subscriptionRenewalDate: "2025-06-01",
  },
  {
    id: "ottobock",
    initials: "OT",
    name: "Ottobock",
    website: "ottobock.com",
    location: "Duderstadt, Germany",
    productCount: 3,
    claimedStatus: "Claimed",
    subscriptionStatus: "Active",
    verificationStatus: "Verified",
    createdAt: "2023-04-15",
    bio: "Global leader in prosthetics, orthotics and human mobility.",
    country: "Germany",
    region: "Lower Saxony",
    city: "Duderstadt",
    products: [
      {
        id: "p-2",
        name: "Michelangelo Hand",
        category: "Bionic Hand",
        status: "Active",
      },
      {
        id: "p-3",
        name: "Genium X3",
        category: "Microprocessor Knee",
        status: "Active",
      },
      {
        id: "p-4",
        name: "C-Leg 4",
        category: "Prosthetic Knee",
        status: "Active",
      },
    ],
    subscriptionPlan: "Annual Enterprise",
    subscriptionStartDate: "2023-04-15",
    subscriptionRenewalDate: "2025-04-15",
  },
  {
    id: "ossur",
    initials: "OS",
    name: "Össur",
    website: "ossur.com",
    location: "Reykjavik, Iceland",
    productCount: 1,
    claimedStatus: "Unclaimed",
    subscriptionStatus: "None",
    verificationStatus: "Unverified",
    createdAt: "2024-01-20",
    bio: "Innovating non-invasive orthopaedics and bionic mobility devices.",
    country: "Iceland",
    region: "Capital Region",
    city: "Reykjavik",
    products: [
      {
        id: "p-5",
        name: "Rheo Knee",
        category: "Bionic Knee",
        status: "Active",
      },
    ],
    subscriptionPlan: "None",
    subscriptionStartDate: "None",
    subscriptionRenewalDate: "None",
  },
  {
    id: "steeper-group",
    initials: "SG",
    name: "Steeper Group",
    website: "steepergroup.com",
    location: "Leeds, United Kingdom",
    productCount: 1,
    claimedStatus: "Claimed",
    subscriptionStatus: "Active",
    verificationStatus: "Verified",
    createdAt: "2023-09-10",
    bio: "Creating life-changing prosthetic and orthotic products.",
    country: "United Kingdom",
    region: "West Yorkshire",
    city: "Leeds",
    products: [
      {
        id: "p-6",
        name: "Bebionic Hand",
        category: "Myoelectric Hand",
        status: "Active",
      },
    ],
    subscriptionPlan: "Annual",
    subscriptionStartDate: "2023-09-10",
    subscriptionRenewalDate: "2025-09-10",
  },
];
