import { BionicProductItem } from "@/types/product";

export const MOCK_PRODUCTS_DATA: BionicProductItem[] = [
  {
    id: "hero-arm",
    name: "Hero Arm",
    pioneerName: "Open Bionics",
    limbCategory: "Upper Limb",
    productType: "Bionic Hand",
    activeUsers: 234,
    status: "Active",
    description: "Lightweight myoelectric bionic arm.",
    tags: [
      "Adaptive-Volume",
      "Ultra-Light",
      "Environment-Proof",
      "Quiet",
      "Great Battery",
      "Style-Ready",
    ],
    verifiedReviewsCount: 234,
  },
  {
    id: "michelangelo-hand",
    name: "Michelangelo Hand",
    pioneerName: "Ottobock",
    limbCategory: "Upper Limb",
    productType: "Bionic Hand",
    activeUsers: 189,
    status: "Active",
    description: "Advanced prosthetic hand with Axon-Bus technology and natural movement.",
    tags: [
      "High-Precision",
      "Ergonomic",
      "Dual-Drive",
      "Durable",
      "Fast Response",
    ],
    verifiedReviewsCount: 189,
  },
  {
    id: "x3-knee",
    name: "X3 Knee",
    pioneerName: "Ottobock",
    limbCategory: "Lower Limb",
    productType: "Bionic Knee",
    activeUsers: 312,
    status: "Active",
    description: "Waterproof, highly robust microprocessor knee joint for extreme mobility.",
    tags: [
      "Fully Waterproof",
      "Microprocessor Control",
      "Stair Ascent",
      "Running Mode",
    ],
    verifiedReviewsCount: 312,
  },
  {
    id: "empower-ankle",
    name: "Empower Ankle",
    pioneerName: "Ottobock",
    limbCategory: "Lower Limb",
    productType: "Bionic Foot",
    activeUsers: 178,
    status: "Active",
    description: "Powered propulsion bionic ankle providing energetic push-off during gait.",
    tags: [
      "Powered Push-Off",
      "Energy Return",
      "Gait Symmetry",
      "Terrain Adaptation",
    ],
    verifiedReviewsCount: 178,
  },
  {
    id: "power-knee",
    name: "Power Knee",
    pioneerName: "Össur",
    limbCategory: "Lower Limb",
    productType: "Bionic Knee",
    activeUsers: 95,
    status: "Active",
    description: "Motor-powered bionic knee with artificial intelligence for active assistance.",
    tags: [
      "Active Assistance",
      "Smart Sensor AI",
      "Muscle Relief",
      "Natural Cadence",
    ],
    verifiedReviewsCount: 95,
  },
  {
    id: "bebionic-hand",
    name: "bebionic Hand",
    pioneerName: "Steeper Group",
    limbCategory: "Upper Limb",
    productType: "Bionic Hand",
    activeUsers: 267,
    status: "Active",
    description: "Multi-articulating myoelectric hand with individual motor per finger.",
    tags: [
      "Multi-Grip",
      "Individual Motors",
      "Proportional Speed",
      "Heavy Duty",
    ],
    verifiedReviewsCount: 267,
  },
];
