import { UserItem } from "@/types/user";

export const MOCK_USERS_DATA: UserItem[] = [
  {
    id: "usr-1",
    name: "Marcus Chen",
    email: "marcus.chen@email.com",
    initials: "MC",
    isYellowAvatar: true,
    profileType: "Active User",
    location: "San Francisco, United States",
    bionicLookingFor: "2 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-03-15",
    accountStatus: "Active",
  },
  {
    id: "usr-2",
    name: "Sofia Reyes",
    email: "sofia.reyes@email.com",
    initials: "SR",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Barcelona, Spain",
    bionicLookingFor: "1 product",
    isBionicProduct: false,
    verificationStatus: "Pending",
    joinedDate: "2024-05-20",
    accountStatus: "Active",
  },
  {
    id: "usr-3",
    name: "James Okafor",
    email: "james.okafor@email.com",
    initials: "JO",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Lagos, Nigeria",
    bionicLookingFor: "Bionic Hand",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-07-08",
    accountStatus: "Active",
  },
  {
    id: "usr-4",
    name: "Lena Müller",
    email: "lena.mueller@email.com",
    initials: "LM",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Munich, Germany",
    bionicLookingFor: "1 product",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-01-12",
    accountStatus: "Active",
  },
  {
    id: "usr-5",
    name: "Aisha Al-Farsi",
    email: "aisha.alfarsi@email.com",
    initials: "AA",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Dubai, UAE",
    bionicLookingFor: "Bionic Knee",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-09-01",
    accountStatus: "Active",
  },
  {
    id: "usr-6",
    name: "Ryan Torres",
    email: "ryan.torres@email.com",
    initials: "RT",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Toronto, Canada",
    bionicLookingFor: "0 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2023-11-30",
    accountStatus: "Suspended",
  },
  // Additional sample data for paginating through realistic pages
  {
    id: "usr-7",
    name: "Elena Rostova",
    email: "elena.rostova@email.com",
    initials: "ER",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Prague, Czechia",
    bionicLookingFor: "3 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-02-18",
    accountStatus: "Active",
  },
  {
    id: "usr-8",
    name: "Kenji Sato",
    email: "kenji.sato@email.com",
    initials: "KS",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Tokyo, Japan",
    bionicLookingFor: "Bionic Arm",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-06-11",
    accountStatus: "Active",
  },
  {
    id: "usr-9",
    name: "Chloe Dupont",
    email: "chloe.dupont@email.com",
    initials: "CD",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Paris, France",
    bionicLookingFor: "1 product",
    isBionicProduct: false,
    verificationStatus: "Pending",
    joinedDate: "2024-04-02",
    accountStatus: "Active",
  },
  {
    id: "usr-10",
    name: "Liam O'Connor",
    email: "liam.oconnor@email.com",
    initials: "LO",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Dublin, Ireland",
    bionicLookingFor: "Bionic Leg",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-08-14",
    accountStatus: "Active",
  },
  {
    id: "usr-11",
    name: "Mateo Silva",
    email: "mateo.silva@email.com",
    initials: "MS",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Lisbon, Portugal",
    bionicLookingFor: "2 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-01-28",
    accountStatus: "Active",
  },
  {
    id: "usr-12",
    name: "Zara Khan",
    email: "zara.khan@email.com",
    initials: "ZK",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "London, UK",
    bionicLookingFor: "Bionic Hand",
    isBionicProduct: true,
    verificationStatus: "Pending",
    joinedDate: "2024-09-19",
    accountStatus: "Active",
  },
];
