import { UserItem } from "@/types/user";

export const MOCK_USERS_DATA: UserItem[] = [
  {
    id: "usr-1",
    name: "Marcus Chen",
    email: "marcus.chen@email.com",
    initials: "MC",
    isYellowAvatar: true,
    profileType: "Active User",
    location: "San Francisco, United States",
    bionicLookingFor: "2 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-03-15",
    accountStatus: "Active",
    age: 34,
    country: "United States",
    region: "California",
    city: "San Francisco",
    bio: "Upper limb amputee. Passionate about bionic technology.",
    bionicProducts: [
      {
        id: "prod-1",
        name: "Hero Arm",
        brand: "Open Bionics",
        category: "Upper Limb",
        status: "Verified",
      },
      {
        id: "prod-2",
        name: "Michelangelo Hand",
        brand: "Ottobock",
        category: "Upper Limb",
        status: "Pending",
      },
    ],
    masterIndicators: {
      originOfAmputation: "Traumatic",
      anatomicalBaseline: "Transradial",
    },
  },
  {
    id: "usr-2",
    name: "Sofia Reyes",
    email: "sofia.reyes@email.com",
    initials: "SR",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Barcelona, Spain",
    bionicLookingFor: "1 product",
    isBionicProduct: false,
    verificationStatus: "Pending",
    joinedDate: "2024-05-20",
    accountStatus: "Active",
    age: 28,
    country: "Spain",
    region: "Catalonia",
    city: "Barcelona",
    bio: "Lower limb bionics enthusiast and community advocate.",
    bionicProducts: [
      {
        id: "prod-3",
        name: "X3 Knee",
        brand: "Ottobock",
        category: "Lower Limb",
        status: "Pending",
      },
    ],
    masterIndicators: {
      originOfAmputation: "Congenital",
      anatomicalBaseline: "Transfemoral",
    },
  },
  {
    id: "usr-3",
    name: "James Okafor",
    email: "james.okafor@email.com",
    initials: "JO",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Lagos, Nigeria",
    bionicLookingFor: "Bionic Hand",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-07-08",
    accountStatus: "Active",
    age: 31,
    country: "Nigeria",
    region: "Lagos State",
    city: "Lagos",
    bio: "Exploring cutting-edge multi-articulating myoelectric hands.",
    bionicProducts: [],
    masterIndicators: {
      originOfAmputation: "Traumatic",
      anatomicalBaseline: "Transradial",
    },
  },
  {
    id: "usr-4",
    name: "Lena Müller",
    email: "lena.mueller@email.com",
    initials: "LM",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Munich, Germany",
    bionicLookingFor: "1 product",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2024-01-12",
    accountStatus: "Active",
    age: 42,
    country: "Germany",
    region: "Bavaria",
    city: "Munich",
    bio: "Biomedical engineer and long-time myoelectric prosthesis user.",
    bionicProducts: [
      {
        id: "prod-4",
        name: "Bebionic Hand",
        brand: "Ottobock",
        category: "Upper Limb",
        status: "Verified",
      },
    ],
    masterIndicators: {
      originOfAmputation: "Traumatic",
      anatomicalBaseline: "Transhumeral",
    },
  },
  {
    id: "usr-5",
    name: "Aisha Al-Farsi",
    email: "aisha.alfarsi@email.com",
    initials: "AA",
    isYellowAvatar: false,
    profileType: "Future User",
    location: "Dubai, UAE",
    bionicLookingFor: "Bionic Knee",
    isBionicProduct: true,
    verificationStatus: "Unverified",
    joinedDate: "2024-09-01",
    accountStatus: "Active",
    age: 26,
    country: "United Arab Emirates",
    region: "Dubai",
    city: "Dubai",
    bio: "Looking for advanced microprocessor knee recommendations.",
    bionicProducts: [],
    masterIndicators: {
      originOfAmputation: "Congenital",
      anatomicalBaseline: "Transfemoral",
    },
  },
  {
    id: "usr-6",
    name: "Ryan Torres",
    email: "ryan.torres@email.com",
    initials: "RT",
    isYellowAvatar: false,
    profileType: "Active User",
    location: "Toronto, Canada",
    bionicLookingFor: "0 products",
    isBionicProduct: false,
    verificationStatus: "Verified",
    joinedDate: "2023-11-30",
    accountStatus: "Suspended",
    age: 39,
    country: "Canada",
    region: "Ontario",
    city: "Toronto",
    bio: "Account currently suspended pending compliance review.",
    bionicProducts: [],
    masterIndicators: {
      originOfAmputation: "Traumatic",
      anatomicalBaseline: "Transtibial",
    },
  },
];
