import { VerificationItem } from "@/types/verification";

export const MOCK_VERIFICATIONS_DATA: VerificationItem[] = [
  {
    id: "verif-1",
    userName: "Marcus Chen",
    userLocation: "San Francisco, US",
    userInitials: "MC",
    isYellowAvatar: true,
    productName: "Michelangelo Hand",
    brand: "Ottobock",
    limb: "Upper Limb",
    submissionDate: "2024-11-28",
    status: "Pending",
    videoDuration: "10-second verification video",
    productHistory: [
      { name: "Hero Arm", status: "Verified" },
      { name: "Michelangelo Hand", status: "Pending" },
    ],
  },
  {
    id: "verif-2",
    userName: "Sofia Reyes",
    userLocation: "Barcelona, Spain",
    userInitials: "SR",
    isYellowAvatar: false,
    productName: "X3 Knee",
    brand: "Ottobock",
    limb: "Lower Limb",
    submissionDate: "2024-11-25",
    status: "Pending",
    videoDuration: "10-second verification video",
    productHistory: [
      { name: "X3 Knee", status: "Pending" },
    ],
  },
  {
    id: "verif-3",
    userName: "Ryan Torres",
    userLocation: "Toronto, Canada",
    userInitials: "RT",
    isYellowAvatar: false,
    productName: "bebionic Hand",
    brand: "Steeper Group",
    limb: "Upper Limb",
    submissionDate: "2024-11-20",
    status: "Unsuccessful",
    videoDuration: "10-second verification video",
    unsuccessfulReason: "Video did not clearly show the prescribed interaction.",
    productHistory: [
      { name: "Hero Arm", status: "Verified" },
      { name: "Michelangelo Hand", status: "Unsuccessful" },
      { name: "bebionic Hand", status: "Unsuccessful" },
    ],
  },
  {
    id: "verif-4",
    userName: "Lena Müller",
    userLocation: "Munich, Germany",
    userInitials: "LM",
    isYellowAvatar: false,
    productName: "Hero Arm",
    brand: "Open Bionics",
    limb: "Upper Limb",
    submissionDate: "2024-10-18",
    status: "Approved",
    videoDuration: "10-second verification video",
    productHistory: [
      { name: "Hero Arm", status: "Verified" },
    ],
  },
  {
    id: "verif-5",
    userName: "Mateo Silva",
    userLocation: "Lisbon, Portugal",
    userInitials: "MS",
    isYellowAvatar: false,
    productName: "Genium Knee",
    brand: "Ottobock",
    limb: "Lower Limb",
    submissionDate: "2024-10-04",
    status: "Approved",
    videoDuration: "10-second verification video",
    productHistory: [
      { name: "Genium Knee", status: "Verified" },
    ],
  },
];
